name: Test Project
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Instal NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Navigate to project folder
        run: cd /home/runner/work/github-actions-course-resources/Code/02\ Basics/02\ Starting Project/src
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test

